FROM node:24.15.0-slim
WORKDIR /src
ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_API_ENDPOINT
ARG VITE_SIGN_IN_REDIRECT
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_API_ENDPOINT=$VITE_API_ENDPOINT
ENV VITE_SIGN_IN_REDIRECT=$VITE_SIGN_IN_REDIRECT
COPY . .
RUN npm install
RUN npm run build
EXPOSE 4200
ENTRYPOINT ["npm", "run", "start"]
